=== carafe-fm/carafe-bundler/schema/meta.schema.json
{
    "$id": "https://carafe.fm/schema/draft-01/meta.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "about": {"type": "string"},
        "bookend": {"type": "string", "minLength": 1},
        "bridgeAPIMethods": {
            "oneOf": [
                {"type": "string"},
                {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "properties": {
                            "callback": {"type": "boolean"},
                            "description": {"type": "string"}
                        },
                        "required": ["callback", "description"]
                    }
                }
            ]
        },
        "category": {"type": "string", "minLength": 1},
        "creator": {"type": "string", "minLength": 1},
        "description": {"type": "string", "minLength": 1},
        "hashLoad": {"$ref": "https://carafe.fm/schema/draft-01/bundle.schema.json#/definitions/boolean"},
        "id": {"type": "string", "format": "uuid"},
        "name": {"type": "string", "minLength": 1},
        "offlineCompatibile": {"$ref": "https://carafe.fm/schema/draft-01/bundle.schema.json#/definitions/boolean"},
        "references": {
            "oneOf": [
                {"type": "string"},
                {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "uri"
                    }
                }
            ]
        },
        "version": {"type": "string", "minLength": 1},
        "windowsTested": {"$ref": "https://carafe.fm/schema/draft-01/bundle.schema.json#/definitions/boolean"}
    },
    "required": [
        "about",
        "bookend",
        "bridgeAPIMethods",
        "category",
        "creator",
        "description",
        "hashLoad",
        "id",
        "name",
        "offlineCompatibile",
        "references",
        "version",
        "windowsTested"
    ]
}

=== carafe-fm/carafe-bundler/test/source-widget/meta.json
{
    "about": "<span style=\"\" >This simple example illustrates the basics of the bundle format.</span>",
    "bookend": "__",
    "bridgeAPIMethods": {},
    "category": "Development",
    "creator": "Jeremiah Small",
    "description": "A very simple starter bundle.",
    "hashLoad": false,
    "id": "1D9AA724-EA93-4E6E-82B2-B83583479B93",
    "name": "Hello World",
    "offlineCompatibile": true,
    "references": [],
    "version": "2.0.0",
    "windowsTested": true
}
